### ISSUE TITLE
When calling enterpip this error is occuring

### ISSUE THREAD

**Issue by ragul-pr** [PuntitOwO/simple_pip_mode_flutter#19]
Failed to handle method call
E/MethodChannel#puntito.simple_pip_mode(14184): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/MethodChannel#puntito.simple_pip_mode(14184): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/MethodChannel#puntito.simple_pip_mode(14184): 	at android.os.Handler.handleCallback(Handler.java:958)
E/MethodChannel#puntito.simple_pip_mode(14184): 	at android.os.Handler.dispatchMessage(Handler.java:99)
I/flutter (14184): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
I/flutter (14184): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)

**Comment by PuntitOwO** [comment]
@ragul-steamA can you paste the `flutter doctor` output and the snippet of code that triggers this error, please?

**Comment by user1121114685** [comment]
````
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Please specify a namespace in the module's build.gradle file like so:

     android {
         namespace 'com.example.namespace'
     }

     If the package attribute is specified in the source AndroidManifest.xml, it can be migrated automatically to the namespace value in the build.gradle file using the AGP Upgrade Assistant; please refer to https://developer.android.com/studio/build/agp-upgrade-assistant for more information.
```

@PuntitOwO at main namespace not change!

**Comment by ragul-steamA** [comment]
ragulpr@Admins-MacBook-Air ev-flutter % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.5, on macOS 15.0 24A335 darwin-arm64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.91.1)
[✓] Connected device (4 available)
    ! Error: Browsing on the local area network for Treesa’s iPhone. Ensure the device is unlocked and attached with a cable or
      associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for Pratheep’s iPhone. Ensure the device is unlocked and attached with a cable
      or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for Sharath iPhone. Ensure the device is unlocked and attached with a cable or
      associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
    ! Error: Browsing on the local area network for KEERTHANA’s iPhone. Ensure the device is unlocked and attached with a cable
      or associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

• No issues found!



onGoVM.pip.enterPipMode()

onGoVM.updateSimplePip(SimplePip());

**Comment by ragul-steamA** [comment]
I/flutter (11230): PlatformException(error, lateinit property activity has not been initialized, null, kotlin.UninitializedPropertyAccessException: lateinit property activity has not been initialized
I/flutter (11230): 	at cl.puntito.simple_pip_mode.SimplePipModePlugin.onMethodCall(SimplePipModePlugin.kt:101)
I/flutter (11230): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
I/flutter (11230): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
I/flutter (11230): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
I/flutter (11230): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
I/flutter (11230): 	at android.os.Handler.handleCallback(Handler.java:959)
I/flutter (11230): 	at android.os.Handler.dispatchMessage(Handler.java:100)
I/flutter (11230): 	at android.os.Looper.loopOnce(Looper.java:232)
I/flutter (11230): 	at android.os.Looper.loop(Looper.java:317)
I/flutter (11230): 	at android.app.ActivityThread.main(ActivityThread.java:8699)
I/flutter (11230): 	at java.lang.reflect.Method.invoke(N
I/flutter (11230): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:651:7)
I/flutter (11230): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
I/flutter (11230): <asynchronous suspension>
I/flutter (11230): #2      SimplePip.enterPipMode (package:simple_pip_mode/simple_pip.dart:55:9)
I/flutter (11230): <asynchronous suspension>



@PuntitOwO  This may give you some additional clarity knidly fix this ASAP. It is prod app.

**Comment by ragul-steamA** [comment]
@PuntitOwO  Can you check again certain devices have this issue.
PlatformException(error, lateinit property activity has not been initialized, null, kotlin.UninitializedPropertyAccessException: lateinit property activity has not been initialized
I/flutter ( 2923): 	at cl.puntito.simple_pip_mode.SimplePipModePlugin.onMethodCall(SimplePipModePlugin.kt:101)
I/flutter ( 2923): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
I/flutter ( 2923): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
I/flutter ( 2923): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
I/flutter ( 2923): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
I/flutter ( 2923): 	at android.os.Handler.handleCallback(Handler.java:958)
I/flutter ( 2923): 	at android.os.Handler.dispatchMessage(Handler.java:99)
I/flutter ( 2923): 	at android.os.Looper.loopOnce(Looper.java:230)
I/flutter ( 2923): 	at android.os.Looper.loop(Looper.java:319)
I/flutter ( 2923): 	at android.app.ActivityThread.main(ActivityThread.java:8919)
I/flutter ( 2923): 	at java.lang.reflect.Method.invoke(Na
I/flutter ( 2923): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:651:7)
I/flutter ( 2923): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
I/flutter ( 2923): <asynchronous suspension>
I/flutter ( 2923): #2      SimplePip.enterPipMode (package:simple_pip_mode/simple_pip.dart:55:9)
I/flutter ( 2923): <asynchronous suspension>

**Comment by ragul-steamA** [comment]
@PuntitOwO  can you check this please.

**Comment by Purehi** [comment]
Any updates?

**Comment by RKSigma** [comment]
E/MethodChannel#puntito.simple_pip_mode(24664): Failed to handle method call
E/MethodChannel#puntito.simple_pip_mode(24664): java.lang.IllegalStateException: Activity must be resumed to enter picture-in-picture
E/MethodChannel#puntito.simple_pip_mode(24664): 	at cl.puntito.simple_pip_mode.SimplePipModePlugin.onMethodCall(SimplePipModePlugin.kt:106)

**Comment by PuntitOwO** [comment]
Feel free to re-open the issue with more info and an MRE
